name: flutter_firebase_chat_core
description: >
  Actively maintained, by me.
version: 1.6.7
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_chat_types:
    git:
      url: https://github.com/andrewkimjoseph/flutter_chat_types
  meta: ^1.9.1

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
